# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_6w-Mw0wYbEGtjrmYvaN7abBW1GBcTB4
"""

def print_board(board):
    print(f"\n {board[0]} | {board[1]} | {board[2]} ")
    print("-----------")
    print(f" {board[3]} | {board[4]} | {board[5]} ")
    print("-----------")
    print(f" {board[6]} | {board[7]} | {board[8]} \n")

def check_winner(board):
    win_conditions = [(0, 1, 2), (3, 4, 5), (6, 7, 8), # Horizontal
                      (0, 3, 6), (1, 4, 7), (2, 5, 8), # Vertical
                      (0, 4, 8), (2, 4, 6)]           # Diagonal
    for condition in win_conditions:
        if board[condition[0]] == board[condition[1]] == board[condition[2]] != " ":
            return board[condition[0]]
    return None

def play_game():
    board = [" "] * 9
    current_player = "X"

    print("Welcome to Tic-Tac-Toe!")
    print("Positions are numbered 0-8 (Top-left to Bottom-right)")

    for turn in range(9):
        print_board(board)

        try:
            move = int(input(f"Player {current_player}, enter position (0-8): "))
            if board[move] != " ":
                print("Position already taken! Try again.")
                continue
        except (ValueError, IndexError):
            print("Invalid input. Please enter a number between 0 and 8.")
            continue

        board[move] = current_player
        winner = check_winner(board)

        if winner:
            print_board(board)
            print(f"Congratulations! Player {winner} wins!")
            return

        current_player = "O" if current_player == "X" else "X"

    print_board(board)
    print("It's a tie!")

# Start the game
play_game()